#ifndef CVX10K_BROWSER_REENABLE_H
#define CVX10K_BROWSER_REENABLE_H

#include "AEEStdDef.h"

#include "AEEInterface.h"

#if !defined(AEEINTERFACE_CPLUSPLUS)

#include "AEEStdDef.h"
#define AEECLSID_CVX10K_BROWSER_REENABLE 0x00B9099D

#else /* C++ */

#include "AEEStdDef.h"

//WARNING: This classID was locally generated by the wizard 6/8/2025
//For commercializing this module, please get a valid ClassID.
const AEECLSID AEECLSID_CVX10K_BROWSER_REENABLE = 0x00B9099D;

#endif /* !defined(AEEINTERFACE_CPLUSPLUS) */

#endif /* #ifndef CVX10K_BROWSER_REENABLE_H */
