#ifndef VX10K_BROWSER_REENABLE_RES_H 
#define VX10K_BROWSER_REENABLE_RES_H 

#define VX10K_BROWSER_REENABLE_RES_FILE "vx10k_browser_reenable.bar"

#define IDS_STRING_1001 1001


#endif  // VX10K_BROWSER_REENABLE_RES_H
